<?php
declare( strict_types = 1 );

namespace AIWP\Designer\ACF;

use AIWP\Designer\Pages\PageRepository;
use AIWP\Designer\Pages\PageSchema;
use AIWP\Designer\Template\FieldReference;

/**
 * Turns stored page schemas into real ACF field groups on acf/init.
 *
 * No PHP files are generated. Nothing is written to the theme.
 */
final class SchemaRegistrar {

	private PageRepository $pages;

	public function __construct( PageRepository $pages ) {
		$this->pages = $pages;
	}

	public function register(): void {
		add_action( 'acf/init', array( $this, 'register_groups' ), 20 );
	}

	/**
	 * Re-register every AIWP field group after a schema has changed.
	 *
	 * ACF keeps registered fields and loaded values in in-memory stores for the
	 * life of the request. Re-adding a group is not enough: a key looked up before
	 * the change stays cached, so writing content straight after changing a schema
	 * silently dropped the fields that moved or were added. Clearing the stores
	 * first makes the new schema real within the same request.
	 */
	public function refresh(): void {
		if ( ! ACFManager::is_available() || ! function_exists( 'acf_get_store' ) ) {
			return;
		}

		foreach ( array( 'fields', 'field-groups', 'values' ) as $store_name ) {
			$store = acf_get_store( $store_name );
			if ( $store ) {
				$store->reset();
			}
		}

		if ( function_exists( 'acf_get_local_store' ) ) {
			foreach ( array( 'fields', 'groups' ) as $store_name ) {
				$store = acf_get_local_store( $store_name );
				if ( $store ) {
					$store->reset();
				}
			}
		}

		/**
		 * Anything else that registers local field groups gets to put them back,
		 * since the stores were just emptied.
		 *
		 * @since 0.3.0
		 */
		do_action( 'aiwp/register_local_fields' );

		$this->register_groups();
	}

	public function register_groups(): void {
		if ( ! ACFManager::is_available() ) {
			return;
		}

		foreach ( $this->pages->all_page_ids() as $page_id ) {
			$schema = $this->pages->schema( $page_id );
			if ( ! $schema instanceof PageSchema ) {
				continue;
			}
			$uuid = $this->pages->uuid( $page_id );
			if ( '' === $uuid ) {
				continue;
			}
			$this->register_page_groups( $page_id, $uuid, $schema );
		}
	}

	/**
	 * The same fields, but on every post of a type rather than on one page.
	 *
	 * An article design is one design for many posts, so its fields cannot be
	 * keyed to a post id. They are keyed to the design instead, and located by
	 * post type.
	 */
	public function register_for_post_type( PageSchema $schema, string $post_type, string $uuid ): void {
		if ( ! ACFManager::is_available() ) {
			return;
		}

		$this->register_page_groups(
			0,
			$uuid,
			$schema,
			array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => $post_type,
					),
				),
			)
		);
	}

	/**
	 * @param array<int,array<int,array<string,string>>>|null $location
	 */
	private function register_page_groups( int $page_id, string $uuid, PageSchema $schema, ?array $location = null ): void {
		$order = 0;

		$location = $location ?? array(
			array(
				array(
					'param'    => 'post',
					'operator' => '==',
					'value'    => (string) $page_id,
				),
			),
		);

		foreach ( $schema->sections() as $section ) {
			$fields = array();

			foreach ( $section['fields'] as $field ) {
				$acf_field = $this->to_acf_field( $uuid, $section['id'], $field );
				if ( null !== $acf_field ) {
					$fields[] = $acf_field;
				}
			}

			if ( array() === $fields ) {
				continue;
			}

			acf_add_local_field_group(
				array(
					'key'                   => FieldKeyGenerator::group_key( $uuid, $section['id'] ),
					'title'                 => sprintf( 'AIWP — %s', $section['label'] ),
					'fields'                => $fields,
					'location'              => $location,
					'menu_order'            => $order++,
					'position'              => 'normal',
					'style'                 => 'default',
					'label_placement'       => 'top',
					'active'                => true,
					'show_in_rest'          => true,
					'description'           => 'Generated by AIWP Designer.',
					'hide_on_screen'        => array(),
				)
			);
		}
	}

	/**
	 * @param array<string,mixed> $field
	 * @return array<string,mixed>|null
	 */
	private function to_acf_field( string $uuid, string $section_id, array $field ): ?array {
		$type = (string) $field['type'];

		if ( ! ACFManager::field_type_exists( $type ) ) {
			return null;
		}

		$acf = array(
			'key'           => FieldKeyGenerator::field_key( $uuid, $section_id . '_' . $field['id'] ),
			'name'          => PageSchema::acf_name( $section_id . '.' . $field['name'] ),
			'label'         => (string) $field['label'],
			'type'          => $type,
			// Whoever fills this box is often the same person editing the
			// template. Saying how the field is written saves a trip.
			'instructions'  => FieldReference::hint(
				$section_id,
				(string) $field['name'],
				$type,
				(string) ( $field['instructions'] ?? '' )
			),
			'required'      => ! empty( $field['required'] ) ? 1 : 0,
			'show_in_rest'  => true,
		);

		switch ( $type ) {
			case 'image':
				$acf['return_format'] = 'id';
				$acf['preview_size']  = 'medium';
				$acf['library']       = 'all';
				break;

			case 'link':
				$acf['return_format'] = 'array';
				break;

			case 'select':
			case 'radio':
			case 'checkbox':
				$acf['choices'] = (array) ( $field['choices'] ?? array() );
				break;

			case 'true_false':
				$acf['ui'] = 1;
				break;

			case 'wysiwyg':
				$acf['media_upload'] = 0;
				$acf['toolbar']      = 'basic';
				break;

			case 'aiwp_repeater':
				$acf['min']        = absint( $field['min'] ?? 0 );
				$acf['max']        = absint( $field['max'] ?? 0 );
				$acf['sub_fields'] = array();
				foreach ( (array) ( $field['sub_fields'] ?? array() ) as $sub ) {
					if ( ! ACFManager::field_type_exists( (string) $sub['type'] ) ) {
						continue;
					}
					$acf['sub_fields'][] = array(
						'key'           => FieldKeyGenerator::sub_field_key( $uuid, $section_id . '_' . $field['id'], $sub['id'] ),
						'name'          => (string) $sub['name'],
						'label'         => (string) $sub['label'],
						'type'          => (string) $sub['type'],
						'instructions'  => self::sub_hint( (string) $sub['name'], (string) $sub['type'], (string) ( $sub['instructions'] ?? '' ) ),
						'required'      => ! empty( $sub['required'] ) ? 1 : 0,
						'return_format' => 'image' === $sub['type'] ? 'id' : ( 'link' === $sub['type'] ? 'array' : '' ),
						'choices'       => (array) ( $sub['choices'] ?? array() ),
					);
				}
				break;
		}

		return $acf;
	}

	/** The same note, for one row inside a repeating list. */
	private static function sub_hint( string $name, string $type, string $existing ): string {
		$code = '<code>' . esc_html( FieldReference::for_sub_field( $name, $type ) ) . '</code>';
		$hint = sprintf(
			/* translators: %s: a template tag, for example {{text:@item.title}} */
			esc_html__( 'In the template: %s', 'aiwp-designer' ),
			$code
		);

		return '' === $existing ? $hint : $existing . '<br>' . $hint;
	}
}
